baseURL = 'https://astu-3703.github.io/welcome'
languageCode = 'en-us'
title = 'Presentations'
theme = ["reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
codeFences = false # 